### PR TITLE
Made changes to third block of 5 words

### PR DESCRIPTION
**Pull request by hasithavarada**
Made changes in the third block of 5 words

### CODE REVIEW

**Review by mihirl97 — COMMENTED** [review]
All values are correct as per the madlibs_list.txt file.

**Review by mihirl97 — APPROVED** [review]
Approving the PR.

**Comment by chandanagirish1998** [comment]
The changes done are good

**Review by chandanagirish1998 — COMMENTED** [review]
the changes made are good

**Pull request merged**
