### PR TITLE
Chandanagirish1998 madlibs

### PR DESCRIPTION
**Pull request by chandanagirish1998**
Values for the placeholders 6-10

### CODE REVIEW

**Comment by hasithavarada** [comment]
The changes are good

**Review by hasithavarada — APPROVED** [review]
Good work

**Comment by mihirl97** [comment]
There is a merge conflict. @chandanagirish1998 can you initiate pull from your end and resolve the merge conflict. After making the changes that resolve the conflict update the pr.

**Review by hasithavarada — APPROVED** [review]
Changes are good

**Review by hasithavarada — APPROVED** [review]
Changes are very good

**Comment by mihirl97** [comment]
Conflicts are merged

**Review by mihirl97 — APPROVED** [review]
All conflicts are merged. It is correct.

**Review by pansays — APPROVED** [review]
Changes made are good

**Comment by mihirl97** [comment]
Since atharva's branch has been merged into main, there is a conflict. Resolved the conflict.

**Pull request merged**
